FROM alpine:3.22
RUN addgroup -g 1000 -S mcp && adduser -u 1000 -S mcp -G mcp
ARG TARGETPLATFORM
COPY --chown=mcp:mcp $TARGETPLATFORM/mcp-vmanomaly /usr/local/bin/mcp-vmanomaly
RUN chmod +x /usr/local/bin/mcp-vmanomaly
USER mcp
WORKDIR /home/mcp
ENTRYPOINT [ "/usr/local/bin/mcp-vmanomaly" ]
